# Generated by Django 5.2.9 on 2026-01-06 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginausuario', '0002_cursorealizado_experiencialaboral_productoacademico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencialaboral',
            name='fechafingestion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='idexperiencialaboral',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
