# Generated by Django 5.2.9 on 2026-01-06 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginausuario', '0003_alter_experiencialaboral_fechafingestion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursorealizado',
            name='idcursorealizado',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='idperfil',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productoacademico',
            name='idproductoacademico',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productolaboral',
            name='idproductoslaborales',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reconocimiento',
            name='idreconocimiento',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='idventagarage',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
