# Generated by Django 5.2.9 on 2026-01-09 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginausuario', '0004_alter_cursorealizado_idcursorealizado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datospersonales',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/'),
        ),
        migrations.AlterField(
            model_name='cursorealizado',
            name='totalhoras',
            field=models.CharField(max_length=100),
        ),
    ]
