# Generated by Django 5.2.9 on 2026-01-09 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginausuario', '0005_datospersonales_foto_alter_cursorealizado_totalhoras'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventagarage',
            name='articulo',
            field=models.FileField(blank=True, null=True, upload_to='articulo_ventagarage/'),
        ),
        migrations.AlterField(
            model_name='cursorealizado',
            name='rutacertificado',
            field=models.FileField(blank=True, null=True, upload_to='certificados_cursos/'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='rutacertificado',
            field=models.FileField(blank=True, null=True, upload_to='certificados_laborales/'),
        ),
        migrations.AlterField(
            model_name='reconocimiento',
            name='rutacertificado',
            field=models.FileField(blank=True, null=True, upload_to='certificados_reconocimientos/'),
        ),
    ]
