# Generated by Django 5.2.9 on 2026-01-27 02:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginausuario', '0006_ventagarage_articulo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventagarage',
            name='fechapublicacion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='articulo',
            field=models.ImageField(blank=True, null=True, upload_to='articulo_ventagarage/'),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='estadoproducto',
            field=models.CharField(choices=[('Excelente', 'Excelente'), ('Bueno', 'Bueno'), ('Regular', 'Regular')], max_length=40),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='valordelbien',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
