# Generated by Django 5.2.9 on 2026-01-27 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginausuario', '0007_ventagarage_fechapublicacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigSeccionesCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mostrar_datos_personales', models.BooleanField(default=True)),
                ('mostrar_experiencia', models.BooleanField(default=True)),
                ('mostrar_reconocimientos', models.BooleanField(default=True)),
                ('mostrar_cursos', models.BooleanField(default=True)),
                ('mostrar_productos_academicos', models.BooleanField(default=True)),
                ('mostrar_productos_laborales', models.BooleanField(default=True)),
                ('mostrar_venta_garage', models.BooleanField(default=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Secciones (CV)',
                'verbose_name_plural': 'Configuración de Secciones (CV)',
            },
        ),
    ]
