# Generated by Django 5.2.9 on 2026-01-27 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginausuario', '0008_configseccionescv'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configseccionescv',
            options={'verbose_name': 'Configuración CV', 'verbose_name_plural': 'Configuración CV'},
        ),
    ]
