# Generated by Django 5.2.9 on 2026-01-27 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginausuario', '0009_alter_configseccionescv_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursorealizado',
            name='descripcioncurso',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='direcciondomiciliaria',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='direcciontrabajo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='cargodesempenado',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='lugarempresa',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='productoacademico',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='productolaboral',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='reconocimiento',
            name='descripcionreconocimiento',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
    ]
