# Generated by Django 5.2.9 on 2026-01-27 23:05

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginausuario', '0010_alter_cursorealizado_descripcioncurso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
        ),
    ]
