# Generated by Django 5.2.9 on 2026-01-27 23:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginausuario', '0011_alter_datospersonales_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='foto',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
