# Generated by Django 5.2.9 on 2026-01-27 23:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginausuario', '0012_alter_datospersonales_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursorealizado',
            name='rutacertificado',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='certificado'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='rutacertificado',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='certificadolaboral'),
        ),
        migrations.AlterField(
            model_name='reconocimiento',
            name='rutacertificado',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='certificadoreconocimiento'),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='articulo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='articulo'),
        ),
    ]
