# Generated by Django 5.2.9 on 2026-01-27 23:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginausuario', '0013_alter_cursorealizado_rutacertificado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursorealizado',
            name='rutacertificado',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='file'),
        ),
    ]
