# Generated by Django 5.2.9 on 2026-01-28 01:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginausuario', '0014_alter_cursorealizado_rutacertificado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursorealizado',
            name='rutacertificado',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='certificado'),
        ),
    ]
