# Generated by Django 5.2.9 on 2026-01-28 02:43

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginausuario', '0015_alter_cursorealizado_rutacertificado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursorealizado',
            name='rutacertificado',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='certificados_cursos/'),
        ),
    ]
