# Generated by Django 5.2.9 on 2026-01-29 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginausuario', '0016_alter_cursorealizado_rutacertificado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursorealizado',
            name='descripcioncurso',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='fechanacimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='descripcionfunciones',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='emailempresa',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='sitiowebempresa',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='productoacademico',
            name='descripcion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='reconocimiento',
            name='descripcionreconocimiento',
            field=models.CharField(max_length=255),
        ),
    ]
