# Generated by Django 5.2.9 on 2026-01-29 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginausuario', '0016_alter_cursorealizado_rutacertificado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursorealizado',
            name='descripcioncurso',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cursorealizado',
            name='rutacertificado',
            field=models.FileField(blank=True, null=True, upload_to='certificados_cursos/'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='direcciondomiciliaria',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='direcciontrabajo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='fechanacimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='cargodesempenado',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='lugarempresa',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='rutacertificado',
            field=models.FileField(blank=True, null=True, upload_to='certificados_laborales/'),
        ),
        migrations.AlterField(
            model_name='productoacademico',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='productolaboral',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reconocimiento',
            name='descripcionreconocimiento',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reconocimiento',
            name='rutacertificado',
            field=models.FileField(blank=True, null=True, upload_to='certificados_reconocimientos/'),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='articulo',
            field=models.ImageField(blank=True, null=True, upload_to='articulo_ventagarage/'),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
    ]
