# Generated by Django 5.2.9 on 2026-01-29 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginausuario', '0018_alter_cursorealizado_descripcioncurso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='fechanacimiento',
            field=models.DateField(),
        ),
    ]
